### ISSUE TITLE
plot/examples: Add more examples for plot

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#110]
Right now vsl.plot supports the following graph types: Bar, Heatmap, Pie, Scatter, Scatter 3D, Surface. We need to add more examples for them!

We are using Python/Plotly as backend so you can check at their [doc](https://plotly.com/) to know more about supported graphs and look for inspiration there!

Feel free to submit any amount of PRs for this issue!

**Comment by urvisinghal** [comment]
Hi I would like to work on it

**Comment by ulises-jeremias** [comment]
Great! Feel free to create any PR for it and ask any question you have about it!

**Comment by 111STAR** [comment]
Hello Ulises.
why don't response recently?
I am waiting your request.
please send me message in telegram. @ulisesjcf
