### ISSUE TITLE
error: duplicate method `show`

### ISSUE THREAD

**Issue by AmitPress** [vlang/vsl#111]
I had updated to the latest version of vsl, and it is showing error while running example files.

In think it is because of the multiple implementations of the same show() method of Plot struct in the `show_default.v` and `show_windows.v` file.

OS: windows 10
V version: V 0.3.1 95f57e9, latest (through v up)

**Comment by ulises-jeremias** [comment]
@AmitPress hey! thanks for submitting the issue! I just fixed it. Should be fixed if you pull latest master! let me know if you find any other issue!
