### ISSUE TITLE
vsl.plot: Convert .sh files to .vsh

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#115]
Seems that is it working on windows for users that have bash installed. So we need to figure out a way to know if bash is installed. Otherwise we need to provide another way of running the scripts that it provides

One way is to migrate all the `.sh` files in the `plot/` dir to `.vsh` instead. That way VSL plot will be using V for mostly everything and just using python to run the plot server, which is a better way of doing it

_Originally posted by @ulises-jeremias in https://github.com/vlang/vsl/issues/78#issuecomment-1272656331_

**Comment by AmitPress** [comment]
I think, for this case, we must use platform independent APIs to translate the .sh files. I am actually trying to figure out how to translate the whole thing in such a way that it does not break in some particular operating systems. Hopefully, soon I will be on the task.

**Comment by AmitPress** [comment]
Me myself had to actually struggled with windows. Then, I moved on wsl.

**Comment by JalonSolov** [comment]
The beauty of .vsh files it that they are V script files, so they will do everything V will do in the same cross-platform manner as regular V programs.

**Comment by ulises-jeremias** [comment]
@AmitPress do you want me to assign this issue to you? we can also split it into different smaller tasks so we can migrate the scripts one by one 👌🏻
