### ISSUE TITLE
dl open for opencl. And other? 

### ISSUE THREAD

**Issue by MatejMagat305** [vlang/vsl#131]
### Describe the feature

I m so sorry for this form, because I can not deside where this topic belong, I have created 2 pull R. ( Opencl1 #129 and  Opencl2 #130 )to question, but I want add this feature to library ..., so I want to add option "dl open" to opencl, but I do not know now whether it is posible because #129 is error and #130 I can not use - I think ... 

### Use Case

In others languages I always be frustrated to link openCL (and other .so) on android, variadic ..., so it would be greate to have dlopen version, this is first version, the handle would be global or some wrap ..., but it must work before that ...

### Proposed Solution

add dl open ..., I was created "prototype"

### Other Information

I have not done manualy, I create small tool for convert "static" to dynamic link (if is wanted i will give you somewhere to git it is not complete because https://github.com/vlang/v/discussions/16909 - I had used "string.split" instead regex ), I was inspirated by https://github.com/krrishnarraj/libopencl-stub and the origin (curent) vsl.vcl ...

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

V 0.3.2 2d8f160

### Environment details (OS name and version, etc.)

OS: linux, Kali GNU/Linux Rolling
Processor: 32 cpus, 64bit, little endian, AMD Ryzen 9 5950X 16-Core Processor
CC version: cc (Debian 12.2.0-13) 12.2.0

getwd: /home/matejmag/Documents/v/examples/add_dynamic/job
vmodules: /home/matejmag/.vmodules
vroot: /home/matejmag/Documents/v
vexe: /home/matejmag/Documents/v/v
vexe mtime: 2023-01-13 13:20:41
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.2 1e401d1.2d8f160

Git version: git version 2.39.0
Git vroot status: weekly.2023.02-18-g2d8f160e-dirty (2 commit(s) behind V master)
.git/config present: true
thirdparty/tcc status: thirdparty-linux-amd64 12f392c3

**Comment by ulises-jeremias** [comment]
Hi @MatejMagat305 thanks for opening this issue! I'll try to help on this next week. I think I have an idea on how to fix your Para, so I'll create a new one using yours as base applying the needed fixes 👌🏻

**Comment by MatejMagat305** [comment]
> Hi @MatejMagat305 thanks for opening this issue! I'll try to help on this next week. I think I have an idea on how to fix your Para, so I'll create a new one using yours as base applying the needed fixes 👌🏻

sorry for reopen and close, I fix some bugs, and if you want you will be able use https://github.com/MatejMagat305/Vlink2Vdlopen unfortunetly it works only for absolute paths ... I recomend mkdir job mv bin to job and then run ...

**Comment by ulises-jeremias** [comment]
@MatejMagat305 thank you! I'll create a separated PR first trying to do it manually and in separated files just to understand how it works and then I'll share it here 👌🏻

**Comment by ulises-jeremias** [comment]
@MatejMagat305 Created a PR with OpenCL working using DL. https://github.com/vlang/vsl/pull/132

The flag to load it Dynamically is `-d dlopencl`

**Comment by ulises-jeremias** [comment]
you can test it using `v -d opendl run examples/vcl_opencl_basic/main_not_ci.v`

**Comment by MatejMagat305** [comment]
@MatejMagat305 when I put exactly this command it was crash, but if I put ` v -d dlopencl . ` so it work, btw it is amazing work! I do not want to mocking, but the all posible pahs is (in C):
```
#if defined(__APPLE__) || defined(__MACOSX)
static const char *default_so_paths[] = {
  "libOpenCL.so",
  "/System/Library/Frameworks/OpenCL.framework/OpenCL"
};
#elif defined(__ANDROID__)
static const char *default_so_paths[] = {
  "/system/lib64/libOpenCL.so",
  "/system/vendor/lib64/libOpenCL.so",
  "/system/vendor/lib64/egl/libGLES_mali.so",
  "/system/vendor/lib64/libPVROCL.so",
  "/data/data/org.pocl.libs/files/lib64/libpocl.so",
  "/system/lib/libOpenCL.so",
  "/system/vendor/lib/libOpenCL.so",
  "/system/vendor/lib/egl/libGLES_mali.so",
  "/system/vendor/lib/libPVROCL.so",
  "/data/data/org.pocl.libs/files/lib/libpocl.so",
  "libOpenCL.so"
};
#elif defined(_WIN32)
static const char *default_so_paths[] = {
  "OpenCL.dll"
};
#elif defined(__linux__)
static const char *default_so_paths[] = {
  "/usr/lib/libOpenCL.so",
  "/usr/local/lib/libOpenCL.so",
  "/usr/local/lib/libpocl.so",
  "/usr/lib64/libOpenCL.so",
  "/usr/lib32/libOpenCL.so",
  "libOpenCL.so"
};
#endif
```
can I translate this function:
```
static int open_libopencl_so()
{
  char *path = NULL, *str = NULL;
  int i;

  if((str=getenv("LIBOPENCL_SO_PATH")) && access_file(str)) {
    path = str;
  }
  else if((str=getenv("LIBOPENCL_SO_PATH_2")) && access_file(str)) {
    path = str;
  }
  else if((str=getenv("LIBOPENCL_SO_PATH_3")) && access_file(str)) {
    path = str;
  }
  else if((str=getenv("LIBOPENCL_SO_PATH_4")) && access_file(str)) {
    path = str;
  }

  if(!path)
  {
    for(i=0; i<(sizeof(default_so_paths) / sizeof(char*)); i++)
    {
      if(access_file(default_so_paths[i]))
      {
        path = (char *) default_so_paths[i];
        break;
      }
    }
  }

  if(path)
  {
    so_handle = dlopen(path, RTLD_LAZY);
    return 0;
  }
  else
  {
    return -1;
  }
}
```
of course to return form, or dlopen in v is so intelligent to work it?

**Comment by ulises-jeremias** [comment]
DLOpen already used LD behind the scenes. We can add it as fallback, but we always need to make sure to use LD paths as default

I think there is a better way. Let me try something

**Comment by ulises-jeremias** [comment]
I'll add it real quick to my PR so we can merge it 👌🏻 I was also looking to that implementation as reference haha

**Comment by ulises-jeremias** [comment]
will use this `LIBOPENCL_SO_PATH="path1:path2:path3"`

**Comment by ulises-jeremias** [comment]
done, feel free to review the PR 👌🏻 I'll merge it asap!

**Comment by ulises-jeremias** [comment]
done!

**Comment by MatejMagat305** [comment]
wow, perfect, thank!
