### ISSUE TITLE
Wrong permutations generated by `vsl.iter.new_permutations_iter`

### ISSUE THREAD

**Issue by impopular-guy** [vlang/vsl#147]
### Describe the bug

Wrong permutations generated by `vsl.iter.new_permutations_iter` when `repeats == data.len`

### Expected Behavior

correct permutations

### Current Behavior

```
[5.0, 6.0, 7.0]
[5.0, 7.0, 6.0]
[5.0, 7.0, 6.0]
[6.0, 5.0, 7.0]
[6.0, 5.0, 7.0]
[6.0, 7.0, 5.0]
```

### Reproduction Steps

```v
module main
import vsl.iter

fn main() {
    mut perms := iter.new_permutations_iter([f64(5), 6, 7], 3)
    for perm in perms {
        println(perm)
    }
}
```

### V version

V 0.3.3 b6ecd63

### Version used

0.1.47 445bcdf

### Environment details (OS name and version, etc.)

```
OS: windows, Microsoft Windows 11 Home Single Language v22621 64-bit
Processor: 8 cpus, 64bit, little endian,
CC version: Error: exec failed (CreateProcess) with code 2: The system cannot find the file specified.
 cmd: cc --version

getwd: C:\Users\dhrit\.vmodules\vsl
vmodules: C:\Users\dhrit\.vmodules
vroot: C:\BIN\v
vexe: C:\BIN\v\v.exe
vexe mtime: 2023-02-14 22:18:12
is vroot writable: true
is vmodules writable: true
V full version: V 0.3.3 9794a23.b6ecd63

Git version: git version 2.35.1.windows.2
Git vroot status: weekly.2023.05-50-gb6ecd634
.git/config present: true
thirdparty/tcc status: thirdparty-windows-amd64 1e6e7c6f
```

**Comment by impopular-guy** [comment]
Checking with [python.itertools.permutations](https://docs.python.org/3/library/itertools.html?highlight=permutation#itertools.permutations) the error is in the following line

https://github.com/vlang/vsl/blob/baffdbc3df5d68f809fe1c28089650e65396b319/iter/perm.v#L58

It should be `o.cycles[i] = n - i`

**Comment by ulises-jeremias** [comment]
thank you! @impopular-guy do you want to create a PR with the fix? will be great to have you as a new contributor 😊 
maybe your fix will allow us to uncomment these tests https://github.com/vlang/vsl/blob/baffdbc3df5d68f809fe1c28089650e65396b319/iter/perm_test.v#L27

**Comment by ulises-jeremias** [comment]
@impopular-guy sure! no problem!
