### ISSUE TITLE
freebsd and openbsd support is withdrawn?

### ISSUE THREAD

**Issue by j-bm** [vlang/vsl#153]
### Describe the bug

mpi, io/h5 files _cflags.c.v have the openbsd and freebsd include (-I) and library (-L) flags removed.

V supports these platforms, is vsl not going forward with these?

Platform support was removed in commit ab77ace

### Expected Behavior

v test io/h5

should link and run correctly.

### Current Behavior

ld: error: unable to find library -lhdf5
ld: error: unable to find library -lhdf5_hl

### Reproduction Steps

cd ~/.vmodules/vsl
v test io/h5/typeshdf5_test.v

### V version

V 0.3.3

### Version used

V 0.3.3 936bced

### Environment details (OS name and version, etc.)

OpenBSD 7.2

**Comment by ulises-jeremias** [comment]
@j-bm hey! thanks for opening an issue. Probably a mistake on my end. Feel free to create a PR adding that support back 😊
