### ISSUE TITLE
`v install vsl` does not install the official `github.com/vlang/vsl` upstream repository 

### ISSUE THREAD

**Issue by ttytm** [vlang/vsl#191]
### Describe the issue

The url on vpm.vlang.io is set to a fork so `v install vsl` does not install the same repository as `v install https://github.com/vlang/vsl`.

The fork does not have tagged versions, aligning the urls would allow to use vsl in a test cases for installing a tag version `v install vsl@v0.1.50`.

I feel the differing urls are not intended.

### Links

https://vpm.vlang.io/packages/vsl

**Comment by ulises-jeremias** [comment]
@medvednikov could you fix it on VPM to point to this repo instead of the old URL?

**Comment by medvednikov** [comment]
Fixed, thanks.
