### ISSUE TITLE
noise: add simplex noise

### ISSUE THREAD

**Issue by PottierLoic** [vlang/vsl#206]
### Describe the feature

Simplex noise is faster than perlin noise when dealing with more than 3 dimensions: O(2^N) versus O(N^2) and have no directional artefacts.

I think it would be a great thing to have (for me at least) 🙂

If it is ok, I can submit a PR with my implementations for 1/2/3/4d.

### Use Case

I try to generate clouds and I think 4d noise can work well.
Even if it doesn't, it will still be nice to have it on vsl.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Version used

latest

### Environment details (OS name and version, etc.)

everything

**Comment by JalonSolov** [comment]
PRs are always welcome.  :-)
