### ISSUE TITLE
Add machine learning algorithms

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#23]

**Comment by shiipou** [comment]
Next year I'll be a PhD student in Artificial Intelligence.
I could list here the algorithms I'll use.
(And some implementations)

I hope to be able to use V in my own work.

**Comment by ulises-jeremias** [comment]
Great! I plan to include a subset of basic machine learning algorithms in VSL and use it as backend to create a library intended purely for machine learning! so everything works for the future creation of it!
