### ISSUE TITLE
Interested to contribute to VSL

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/vsl#24]
I've contacted you (@ulises-jeremias) in the Discord server, expressing my interest to contribute in this repository. Once V 0.2. is out or wherever work on VSL resumes, I request you to reach out to me on Discord or here and involve me in the proceedings of VSL.

A few of my suggestions for VSL are:
1. Create a roadmap for various components.
2. Complete the linear algebra module and refine the API to be easily usable for end users. (For example, overloading operators for `Matrix`, and so on.)
3. Update the documentation. There are a lot of modules are undocumented but are useful for scientific and compute purposes.

I'll be happy to contribute to VSL substantially. The only requirement is coordination.

**Comment by ulises-jeremias** [comment]
Hey @hungrybluedev , docs are updated now! Generated on every commit to master branch. You can take a look here: https://vlang.github.io/vsl/

Obviously there is a lot to improve, and also, I didn't create the operators for `Matrix` yet (as you mentioned above). I think it is a really good first PR that you can do to start doing contributions and learning the code and more. Also, next week I'll create a roadmap for version 0.2 so we will have cleaner goals for the library

**Comment by hungrybluedev** [comment]
I will take some time to study the codebase. I'm sure it has changed a lot. By the time the roadmap is complete, I will have picked a project to work on.

Additionally, it would be nice to have a medium for consistent communication. Platforms like Discord or Slack would be nice. Let me know what you find comfortable and  we'll get started.
