### ISSUE TITLE
undefined reference to `cblas_ddot' collect2: error

### ISSUE THREAD

**Issue by kahsa** [vlang/vsl#28]
On ArchLinux,  run `./bin/test` returns this error.
```sh
.....
OK   [11/12]  3329.294 ms vmath/math_test.v
FAIL [12/12] 18339.938 ms stats/stats_test.v
==================
stats_test.18334712286288185749.tmp.c:(.text+0x2e10c): undefined reference to `cblas_ddot'
collect2: error: ld returned 1 exit status
```

**Comment by kahsa** [comment]
updated and worked! thanks

**Comment by ulises-jeremias** [comment]
hey @ka-weihe ! just updated the README. The final solution for the openblas issues was to change deps using `openblas-lapack` from AUR instead. 
![image](https://user-images.githubusercontent.com/17727170/103971912-8d00c600-514a-11eb-9d6e-a132d2071809.png)
