### ISSUE TITLE
Mention OpenSSL as a dependency in the README

### ISSUE THREAD

**Issue by hungrybluedev** [vlang/vsl#29]
**VSL version:** Not installed yet
**OS:** Linux (PopOS - based on Ubuntu 20.10)

**What did you do?**
I tried to install VSL through the VPM. I am not using Docker.

**What did you expect to see?**
VSL installing normally.
 
**What did you see instead?**
Error message:

```
cannot compile `/home/astro/v/cmd/tools/vpm.v`: 
/home/astro/v/thirdparty/cJSON/cJSON.o not found, building it in /home/astro/.vmodules/cache/2c/2c7177cc86c8886a18a3f8b893aae32d.o ...

Compilation with tcc failed. Retrying with cc ...
builder error: Header file <openssl/rand.h>, needed for module `net.openssl` was not found. Please install OpenSSL development headers.
```

I suppose it would be worthwhile to mention OpenSSL as a dependency in the readme.

**Comment by hungrybluedev** [comment]
Running `sudo apt install libssl-dev` fixed the issue.

**Comment by ulises-jeremias** [comment]
Thanks! I didn't notice that dep! do you want to do a PR fixing it?

**Comment by mars-json** [comment]
V UI also requires, for some reason, OpenSSL:
```
$ v up
Updating V...
V is already updated.
Current V version: V 0.2.4 c01a8a1, timestamp: 2022-05-15 18:28:37 +0300

$ v install ui
failed    cmd: '/home/vadim/vlang/v/v' -skip-unused '/home/vadim/vlang/v/cmd/tools/vpm.v'
failed   code: 1
builder error: 'openssl/rand.h' not found
```

**Comment by mars-json** [comment]
Executing command  `sudo apt install libssl-dev` fixes installation process.
I have Ubuntu 21.10 OS.
```
$ v install ui
Installing module "ui" from "https://github.com/vlang/ui" to "/home/vadim/.vmodules/ui" ...
```

**Comment by mars-json** [comment]
@ulises-jeremias should dependency for `libssl-dev` be added to Readme/dependency list?

**Comment by YamilBrachoIn** [comment]
Hi, I keep on looking for answer and I found this
brew install openssl
and this made the trick!!!!
