### ISSUE TITLE
Implement Open BLAS in pure V

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#40]
C interop is causing some issues when dealing with OpenBLAS. I think it is time to rewrite the entire library to use pure V instead.

**Comment by natemcintosh** [comment]
I agree on this one. Although re-implementing Open BLAS also sounds like something that requires a comprehensive test suite. Does Open BLAS have a test suite that we could try to copy?

**Comment by ulises-jeremias** [comment]
I don't know exactly about Open BLAS, but I know that https://github.com/gonum/gonum has a really good test suite on their pure GO implementation of BLAS so I think we can use those tests first and then add more in the future 👌🏻

**Comment by ulises-jeremias** [comment]
I started the implementation on branch `feature/vlas`. Will take time but the benefits will be huge
