### ISSUE TITLE
Feature Request: Interpolation functions

### ISSUE THREAD

**Issue by LouisSchmieder** [vlang/vsl#41]
linear interpolation, cubic interpolation & spline interpolation

https://en.wikipedia.org/wiki/Interpolation

- [x] Cubic Interpolation
- [x] Quadratic Interpolation
- [x] Data Interpolation

**Comment by ulises-jeremias** [comment]
@LouisSchmieder I'm starting with this feature right now as part of the module `vsl.fun`. I'll push everything on branch https://github.com/vlang/vsl/tree/feature/interpolation and I'll create a PR to merge to master just to give visibillity of the work done

**Comment by ulises-jeremias** [comment]
Just created this PR https://github.com/vlang/vsl/pull/43

CIs are failling since master is having some issues with tests passing with C interop. It is not related with this feature

**Comment by ulises-jeremias** [comment]
@LouisSchmieder I just finished all types of interpolation on `vsl.fun` with tests
