### ISSUE TITLE
iter: Tests are not passing for ProductIterator using autofree

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#44]
**VSL version:** 0.1.36
**OS:** ArchLinux (Linux)

**What did you do?**

Executed `./bin/test --use-autofree`

**What did you expect to see?**

Expected the tests to pass using `autofree`
 
**What did you see instead?**

![image](https://user-images.githubusercontent.com/17727170/120111266-a6c99680-c147-11eb-9157-c01f0b127637.png)

**Comment by ulises-jeremias** [comment]
@natemcintosh probably you could be interested on solving this one 👌🏻

**Comment by natemcintosh** [comment]
Yea, I can reproduce this pretty easily. However, it doesn't happen when not running with `--use-autofree`. I don't know enough about the `v` compiler to say why this might happen. 

Do you have any suggestions?

**Comment by ulises-jeremias** [comment]
@natemcintosh yeah, I saw that too but I'm not really sure why it is happening. I'll try to debug it and see if I can give more context to solve it 👌🏻

**Comment by ulises-jeremias** [comment]
@natemcintosh Seems that all is passing with `-gc boehm`, so I assume the problem is that autofree is not stable enough yet. I'll close this issue for now
