### ISSUE TITLE
(knn.v) Change error type, fix typos and fix KNN to properly handle ties when k = 1.

### ISSUE THREAD

**Issue by lucasrdrgs** [vlang/vsl#47]
Please, assign me to this issue. I'll be working on it.
Change `.efailed` to `.einval` in knn.v when handling panics;
There **is** still a chance to have ties in `knn.predict` so I must change it so that if there is a tie when k = 1, use the first closest neighbor it finds as the result for the prediction.
Fix a few typos in `knn.v` and in `data.v`

**Comment by lucasrdrgs** [comment]
Should be fixed by my latest PR. It passed the tests and does not get stuck in an infinite loop trying to break ties as far as I have tested. Let me know about any other potential typos or little mistakes like these.

**Comment by ulises-jeremias** [comment]
I'll close this one since @lucasrdrgs already solved the issue 👌🏻
