### ISSUE TITLE
vsl.vmath: Add q_rsqrt function to vmath

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#54]
- [ ] Create file `vmath/vimpl/q_rsqrt.v` with an implementation for function `q_rsqrt`
- [ ] Create file `vmath/vimpl/q_rsqrt_test.v` with tests for the new function
- [ ] Add function entry on files `vmath/math_d_vmath.v` and `vmath/math_notd_vmath.v` to make it possible to use it with all backends

- - -

### CONTRIBUTING

- Read contribution guide [here](https://github.com/vlang/vsl/blob/master/CONTRIBUTING.md)

**Comment by lucasrdrgs** [comment]
Have you started working on q_rsqrt yet? If not, I can work on an implementation!

**Comment by ulises-jeremias** [comment]
@lucasrdrgs not yet! so feel free to start on it 👌🏻 there are some notes about were to do the implementation on the description of this issue 🔥

**Comment by lucasrdrgs** [comment]
Cool, I'm just finishing tf-idf for the upcoming NLP tools and I'll be on my way to write the code for `q_rsqrt`.

**Comment by lucasrdrgs** [comment]
To anyone interested in using q_rsqrt: fast inverse square root has been implemented in commit a991147. `math_d_vmath.v` and `math_notd_vmath.v` haven't been changed yet, so use it at your own discretion.
