### ISSUE TITLE
Add plot libray

### ISSUE THREAD

**Issue by ulises-jeremias** [vlang/vsl#7]
Decide if this is better to use matplotlib-cpp or python-matplotlib as in gosl

**Comment by shiipou** [comment]
The `matplotlib-cpp` use the `python-matplotlib`. 
I'm wrong ?

**Comment by ulises-jeremias** [comment]
You are right! The difference is that gosl's approach is to generate the python code necessary to plot things.
It would be useful to evaluate other possibilities that are better than those and to evaluate what other tools exist to define this module.

**Comment by ulises-jeremias** [comment]
will close this issue until more important stuff is finished
